// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: gRPC/proto/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseType int32

const (
	ResponseType_SUCCESS      ResponseType = 0
	ResponseType_FAILED       ResponseType = 1
	ResponseType_EXPIRED_DATE ResponseType = 2
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "EXPIRED_DATE",
	}
	ResponseType_value = map[string]int32{
		"SUCCESS":      0,
		"FAILED":       1,
		"EXPIRED_DATE": 2,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_proto_auth_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_gRPC_proto_auth_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{0}
}

type AuthData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nam   string                 `protobuf:"bytes,1,opt,name=nam,proto3" json:"nam,omitempty"`
	// proto need unique key number value
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CreateDate    int64  `protobuf:"varint,3,opt,name=createDate,proto3" json:"createDate,omitempty"`
	ExpireDate    int64  `protobuf:"varint,4,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthData.ProtoReflect.Descriptor instead.
func (*AuthData) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthData) GetNam() string {
	if x != nil {
		return x.Nam
	}
	return ""
}

func (x *AuthData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthData) GetCreateDate() int64 {
	if x != nil {
		return x.CreateDate
	}
	return 0
}

func (x *AuthData) GetExpireDate() int64 {
	if x != nil {
		return x.ExpireDate
	}
	return 0
}

type Verify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseType           `protobuf:"varint,1,opt,name=status,proto3,enum=ResponseType" json:"status,omitempty"`
	Auth          *AuthData              `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify) Reset() {
	*x = Verify{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify) ProtoMessage() {}

func (x *Verify) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify.ProtoReflect.Descriptor instead.
func (*Verify) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Verify) GetStatus() ResponseType {
	if x != nil {
		return x.Status
	}
	return ResponseType_SUCCESS
}

func (x *Verify) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

type CreateTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is something like type of proto
	Auth          *AuthData `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenReq) Reset() {
	*x = CreateTokenReq{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenReq) ProtoMessage() {}

func (x *CreateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenReq.ProtoReflect.Descriptor instead.
func (*CreateTokenReq) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenReq) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

type CreateTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AuthData              `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRes) Reset() {
	*x = CreateTokenRes{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRes) ProtoMessage() {}

func (x *CreateTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRes.ProtoReflect.Descriptor instead.
func (*CreateTokenRes) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTokenRes) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

type VerifyTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             *Verify                `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRes) Reset() {
	*x = VerifyTokenRes{}
	mi := &file_gRPC_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRes) ProtoMessage() {}

func (x *VerifyTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRes.ProtoReflect.Descriptor instead.
func (*VerifyTokenRes) Descriptor() ([]byte, []int) {
	return file_gRPC_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyTokenRes) GetV() *Verify {
	if x != nil {
		return x.V
	}
	return nil
}

var File_gRPC_proto_auth_proto protoreflect.FileDescriptor

const file_gRPC_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x15gRPC/proto/auth.proto\"r\n" +
	"\bAuthData\x12\x10\n" +
	"\x03nam\x18\x01 \x01(\tR\x03nam\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"createDate\x18\x03 \x01(\x03R\n" +
	"createDate\x12\x1e\n" +
	"\n" +
	"expireDate\x18\x04 \x01(\x03R\n" +
	"expireDate\"N\n" +
	"\x06Verify\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.ResponseTypeR\x06status\x12\x1d\n" +
	"\x04auth\x18\x02 \x01(\v2\t.AuthDataR\x04auth\"/\n" +
	"\x0eCreateTokenReq\x12\x1d\n" +
	"\x04auth\x18\x01 \x01(\v2\t.AuthDataR\x04auth\"/\n" +
	"\x0eCreateTokenRes\x12\x1d\n" +
	"\x04auth\x18\x01 \x01(\v2\t.AuthDataR\x04auth\"&\n" +
	"\x0eVerifyTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\x0eVerifyTokenRes\x12\x15\n" +
	"\x01v\x18\x01 \x01(\v2\a.VerifyR\x01v*9\n" +
	"\fResponseType\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\x10\n" +
	"\fEXPIRED_DATE\x10\x022m\n" +
	"\vAuthService\x12.\n" +
	"\n" +
	"CreateAuth\x12\x0f.CreateTokenReq\x1a\x0f.CreateTokenRes\x12.\n" +
	"\n" +
	"VerifyAuth\x12\x0f.VerifyTokenReq\x1a\x0f.VerifyTokenResB\aZ\x05/authb\x06proto3"

var (
	file_gRPC_proto_auth_proto_rawDescOnce sync.Once
	file_gRPC_proto_auth_proto_rawDescData []byte
)

func file_gRPC_proto_auth_proto_rawDescGZIP() []byte {
	file_gRPC_proto_auth_proto_rawDescOnce.Do(func() {
		file_gRPC_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_proto_auth_proto_rawDesc), len(file_gRPC_proto_auth_proto_rawDesc)))
	})
	return file_gRPC_proto_auth_proto_rawDescData
}

var file_gRPC_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gRPC_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gRPC_proto_auth_proto_goTypes = []any{
	(ResponseType)(0),      // 0: ResponseType
	(*AuthData)(nil),       // 1: AuthData
	(*Verify)(nil),         // 2: Verify
	(*CreateTokenReq)(nil), // 3: CreateTokenReq
	(*CreateTokenRes)(nil), // 4: CreateTokenRes
	(*VerifyTokenReq)(nil), // 5: VerifyTokenReq
	(*VerifyTokenRes)(nil), // 6: VerifyTokenRes
}
var file_gRPC_proto_auth_proto_depIdxs = []int32{
	0, // 0: Verify.status:type_name -> ResponseType
	1, // 1: Verify.auth:type_name -> AuthData
	1, // 2: CreateTokenReq.auth:type_name -> AuthData
	1, // 3: CreateTokenRes.auth:type_name -> AuthData
	2, // 4: VerifyTokenRes.v:type_name -> Verify
	3, // 5: AuthService.CreateAuth:input_type -> CreateTokenReq
	5, // 6: AuthService.VerifyAuth:input_type -> VerifyTokenReq
	4, // 7: AuthService.CreateAuth:output_type -> CreateTokenRes
	6, // 8: AuthService.VerifyAuth:output_type -> VerifyTokenRes
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gRPC_proto_auth_proto_init() }
func file_gRPC_proto_auth_proto_init() {
	if File_gRPC_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_proto_auth_proto_rawDesc), len(file_gRPC_proto_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_proto_auth_proto_goTypes,
		DependencyIndexes: file_gRPC_proto_auth_proto_depIdxs,
		EnumInfos:         file_gRPC_proto_auth_proto_enumTypes,
		MessageInfos:      file_gRPC_proto_auth_proto_msgTypes,
	}.Build()
	File_gRPC_proto_auth_proto = out.File
	file_gRPC_proto_auth_proto_goTypes = nil
	file_gRPC_proto_auth_proto_depIdxs = nil
}
